Importing Necessary Libraries:

In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

## Loading the Dataset:

In [2]:
iris = datasets.load_iris()
X = iris.data
Y = iris.target

## Visualizing the Dataset:

In [14]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [15]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [16]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

## Splitting the Dataset:

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

## Building the AdaBoost Model: 

In [21]:
from sklearn.ensemble import AdaBoostClassifier 
adb = AdaBoostClassifier()
model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred

array([2, 0, 2, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 1, 2, 2, 0, 0, 2, 0, 1,
       2, 1, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 2, 0, 1, 0, 0, 2, 1, 1,
       0])

## Evaluating the Model

In [22]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))

[[12  0  0]
 [ 0 15  1]
 [ 0  4 13]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.79      0.94      0.86        16
          2       0.93      0.76      0.84        17

avg / total       0.90      0.89      0.89        45

0.8888888888888888


<hr></hr>

## Parameters Tuning:
The most important parameters of AdaBoost are:
- base_estimator
- n_estimators
- learning_rate

In [26]:
"""Using SVM as a base estimator"""
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier 
svc = SVC(probability = True, kernel='linear')
adb = AdaBoostClassifier(n_estimators=100,base_estimator = svc, learning_rate= 0.01)

## Training and Predicting the AdaBoost Classifier

In [30]:
model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred

array([2, 0, 2, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 1, 2, 2, 0, 0, 2, 0, 1,
       2, 2, 0, 1, 1, 0, 1, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 2, 1, 1,
       0])

## Evaluating the Model:

In [33]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))

[[12  0  0]
 [ 0 15  1]
 [ 0  1 16]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.94      0.94      0.94        16
          2       0.94      0.94      0.94        17

avg / total       0.96      0.96      0.96        45

0.9555555555555556
